<h1>Privilege</h1>

<br />

<p>
	<a href="<?php echo $this->url('sonacl-admin/default', array('controller' => 'privileges', 'action' => 'new')); ?>">Novo</a>
</p>

<table class="table">
	<tr>
		<td>ID</td>
		<td>Role</td>
		<td>Nome</td>
		<td>Resource</td>
		<td>Ação</td>
	</tr>
	<?php foreach ($this->data as $entity) : ?>
			<tr>
				<td><?php echo $entity->getId(); ?></td>
				<td><?php echo $entity->getRole()->getNome(); ?></td>
				<td><?php echo $entity->getNome(); ?></td>
				<td><?php echo $entity->getResource()->getNome(); ?></td>
				<td>
					<a href="<?php echo $this->url('sonacl-admin/default', array('controller' => 'privileges', 'action' => 'edit', 'id' => $entity->getId())); ?>">Editar</a> 
					<a href="<?php echo $this->url('sonacl-admin/default', array('controller' => 'privileges', 'action' => 'delete', 'id' => $entity->getId())); ?>">Deletar</a>
				</td>
			</tr>
	<?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>